FROM php:8.3-cli

RUN apt-get update -qq && apt-get install -yq libsqlite3-dev libpq-dev \
    && docker-php-ext-install pdo pdo_sqlite pdo_pgsql pcntl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
